name: udisks2
version: 2.9.4
summary: Storage devices management service
description: |
    Udisks2 provides a dbus service that can query and manager
    storages devices as well as a command-line tool.
confinement: strict
base: core22

slots:
  udisks2-dbus:
    interface: dbus
    bus: system
    name: org.freedesktop.UDisks2

  udisks2:
    udev-file: lib/udev/rules.d/80-udisks2.rules

plugs:
  udisks2-client:
    interface: udisks2

  polkit:
    action-prefix: org.freedesktop.udisks2

apps:
  udisksd:
    command: usr/libexec/udisks2/udisksd
    daemon: dbus
    plugs:
      - hardware-observe
      - mount-observe
      - polkit
    slots:
      - udisks2
    daemon-scope: system
    activates-on:
      - udisks2-dbus

  udisksctl:
    command: usr/bin/udisksctl
    plugs:
      - udisks2-client

layout:
  /usr/var/lib/udisks2:
    bind: $SNAP/usr/var/lib/udisks2
  /usr/etc/udisks2:
    bind: $SNAP/usr/etc/udisks2
  /etc/libblockdev/conf.d:
    bind: $SNAP/etc/libblockdev/conf.d

parts:

  udisks2:
    build-environment:
      - XDG_DATA_DIRS: "/usr/local/share/:/usr/share/:${CRAFT_STAGE}/usr/share/"
    build-packages:
      - meson
      - pkg-config
      - libglib2.0-dev
      - libgudev-1.0-dev
      - libblockdev-dev
      - libatasmart-dev
      - libblockdev-part-dev
      - libblockdev-loop-dev
      - libblockdev-swap-dev
      - libblockdev-mdraid-dev
      - libblockdev-fs-dev
      - libblockdev-crypto-dev
      - libpolkit-agent-1-dev
      - libpolkit-gobject-1-dev
      - gettext
      - xsltproc
      - docbook-xsl
      - polkitd
    stage-packages:
      - libpolkit-agent-1-0
      - libpolkit-gobject-1-0
      - libgudev-1.0-0
      - libblockdev2
      - libblockdev-utils2
      - libatasmart4
      - libblockdev-swap2
      - libblockdev-loop2
      - libblockdev-part2
      - libblockdev-loop2
      - libblockdev-swap2
      - libblockdev-mdraid2
      - libblockdev-fs2
      - libblockdev-crypto2
    plugin: autotools
    autotools-configure-parameters:
      - --prefix=/usr
      - --enable-fhs-media
    source-type: tar
    source: https://github.com/storaged-project/udisks/releases/download/udisks-2.9.4/udisks-2.9.4.tar.bz2
    override-pull: |
      craftctl default
      patch -p1 <"${CRAFT_PROJECT_DIR}/proc-mountinfo.patch"

  policy:
    plugin: nil
    after:
      - udisks2
    override-build: |
      install -Dm644 \
        "${CRAFT_STAGE}/usr/share/polkit-1/actions/org.freedesktop.UDisks2.policy" \
        "${CRAFT_PART_INSTALL}/meta/polkit/polkit.org.freedesktop.UDisks2.policy"
